name: Build and Publish NuGet

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --no-build --configuration Release Oibi.TestHelper/Oibi.TestHelper.csproj --output .

    - name: Push
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.x'
        source-url: https://api.nuget.org/v3/index.json
      env:
        NUGET_API_KEY: ${{secrets.NUGET_API_KEY}}
      run: dotnet nuget push Oibi.TestHelper.*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
