# https://github.com/marketplace/actions/publish-nuget
name: NuGet Generation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    name: Update NuGet
    steps:
      - uses: actions/checkout@v2
      - uses: rohith/publish-nuget@v2
        with:
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
          TAG_COMMIT: false
