
name: NuGet Generation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    name: Update NuGet
    steps:
      - uses: actions/checkout@v2
      - name: publish on version change
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: Oibi.TestHelper/Oibi.TestHelper.csproj
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
